#targets:
#  $default:
#    sources:
#      - "$package$"
#      - "lib/**"
#      - "test/**"
#    builders:
#      drift_dev:
#        generate_for:
#          - "test/**"
#          - "test/**.g.dart"
#        options:
#          store_date_time_values_as_text: true
#          case_from_dart_to_sql: camelCase
# modular code generation setup
targets:
  $default:
    sources:
      - "$package$"
      - "lib/**"
      - "test/**"
    builders:
      drift_dev:
        enabled: false
      drift_dev:analyzer:
        enabled: true
        options: &options
          store_date_time_values_as_text: true
          case_from_dart_to_sql: camelCase
      drift_dev:modular:
        enabled: true
        options: *options