// Mocks generated by Mockito 5.4.4 from annotations
// in floor2drift/test/dart_test/expression_converter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:_fe_analyzer_shared/src/types/shared_type.dart' as _i15;
import 'package:analyzer/dart/element/element.dart' as _i4;
import 'package:analyzer/dart/element/element2.dart' as _i3;
import 'package:analyzer/dart/element/nullability_suffix.dart' as _i13;
import 'package:analyzer/dart/element/type.dart' as _i8;
import 'package:analyzer/dart/element/type_visitor.dart' as _i14;
import 'package:analyzer/file_system/file_system.dart' as _i11;
import 'package:analyzer/source/file_source.dart' as _i20;
import 'package:analyzer/source/source.dart' as _i9;
import 'package:analyzer/src/generated/engine.dart' as _i2;
import 'package:analyzer/src/generated/utilities_dart.dart' as _i7;
import 'package:floor2drift/src/entity/class_state.dart' as _i10;
import 'package:floor2drift/src/enum/enums.dart' as _i18;
import 'package:floor2drift/src/sql/expression_converter/expression_converter.dart'
    as _i16;
import 'package:floor2drift/src/value_response.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:source_span/src/file.dart' as _i5;
import 'package:source_span/src/span.dart' as _i6;
import 'package:sqlparser/sqlparser.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnalysisContext_0 extends _i1.SmartFake
    implements _i2.AnalysisContext {
  _FakeAnalysisContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeElementKind_1 extends _i1.SmartFake implements _i3.ElementKind {
  _FakeElementKind_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeElement_2 extends _i1.SmartFake implements _i4.Element {
  _FakeElement_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSourceFile_3 extends _i1.SmartFake implements _i5.SourceFile {
  _FakeSourceFile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileLocation_4 extends _i1.SmartFake implements _i5.FileLocation {
  _FakeFileLocation_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSpan_5 extends _i1.SmartFake implements _i5.FileSpan {
  _FakeFileSpan_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSourceSpan_6 extends _i1.SmartFake implements _i6.SourceSpan {
  _FakeSourceSpan_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeParameterElement_7 extends _i1.SmartFake
    implements _i4.ParameterElement {
  _FakeParameterElement_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFormalParameterElement_8 extends _i1.SmartFake
    implements _i3.FormalParameterElement {
  _FakeFormalParameterElement_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeParameterKind_9 extends _i1.SmartFake implements _i7.ParameterKind {
  _FakeParameterKind_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDartType_10 extends _i1.SmartFake implements _i8.DartType {
  _FakeDartType_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAugmentedEnumElement_11 extends _i1.SmartFake
    implements _i4.AugmentedEnumElement {
  _FakeAugmentedEnumElement_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterfaceType_12 extends _i1.SmartFake implements _i8.InterfaceType {
  _FakeInterfaceType_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompilationUnitElement_13 extends _i1.SmartFake
    implements _i4.CompilationUnitElement {
  _FakeCompilationUnitElement_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLibraryElement_14 extends _i1.SmartFake
    implements _i4.LibraryElement {
  _FakeLibraryElement_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSource_15 extends _i1.SmartFake implements _i9.Source {
  _FakeSource_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClassState_16 extends _i1.SmartFake implements _i10.ClassState {
  _FakeClassState_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFieldElement_17 extends _i1.SmartFake implements _i4.FieldElement {
  _FakeFieldElement_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_18 extends _i1.SmartFake implements Uri {
  _FakeUri_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_19 extends _i1.SmartFake implements _i11.File {
  _FakeFile_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimestampedData_20<E> extends _i1.SmartFake
    implements _i2.TimestampedData<E> {
  _FakeTimestampedData_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Element].
///
/// See the documentation for Mockito's code generation for more information.
class MockElement extends _i1.Mock implements _i4.Element {
  @override
  List<_i4.Element> get children => (super.noSuchMethod(
        Invocation.getter(#children),
        returnValue: <_i4.Element>[],
        returnValueForMissingStub: <_i4.Element>[],
      ) as List<_i4.Element>);

  @override
  _i2.AnalysisContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeAnalysisContext_0(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeAnalysisContext_0(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.AnalysisContext);

  @override
  String get displayName => (super.noSuchMethod(
        Invocation.getter(#displayName),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
      ) as String);

  @override
  bool get hasAlwaysThrows => (super.noSuchMethod(
        Invocation.getter(#hasAlwaysThrows),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDeprecated => (super.noSuchMethod(
        Invocation.getter(#hasDeprecated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDoNotStore => (super.noSuchMethod(
        Invocation.getter(#hasDoNotStore),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDoNotSubmit => (super.noSuchMethod(
        Invocation.getter(#hasDoNotSubmit),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasFactory => (super.noSuchMethod(
        Invocation.getter(#hasFactory),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasImmutable => (super.noSuchMethod(
        Invocation.getter(#hasImmutable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasInternal => (super.noSuchMethod(
        Invocation.getter(#hasInternal),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasIsTest => (super.noSuchMethod(
        Invocation.getter(#hasIsTest),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasIsTestGroup => (super.noSuchMethod(
        Invocation.getter(#hasIsTestGroup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasJS => (super.noSuchMethod(
        Invocation.getter(#hasJS),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasLiteral => (super.noSuchMethod(
        Invocation.getter(#hasLiteral),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMustBeConst => (super.noSuchMethod(
        Invocation.getter(#hasMustBeConst),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMustBeOverridden => (super.noSuchMethod(
        Invocation.getter(#hasMustBeOverridden),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMustCallSuper => (super.noSuchMethod(
        Invocation.getter(#hasMustCallSuper),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasNonVirtual => (super.noSuchMethod(
        Invocation.getter(#hasNonVirtual),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasOptionalTypeArgs => (super.noSuchMethod(
        Invocation.getter(#hasOptionalTypeArgs),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasOverride => (super.noSuchMethod(
        Invocation.getter(#hasOverride),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasProtected => (super.noSuchMethod(
        Invocation.getter(#hasProtected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasRedeclare => (super.noSuchMethod(
        Invocation.getter(#hasRedeclare),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasReopen => (super.noSuchMethod(
        Invocation.getter(#hasReopen),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasRequired => (super.noSuchMethod(
        Invocation.getter(#hasRequired),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasSealed => (super.noSuchMethod(
        Invocation.getter(#hasSealed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasUseResult => (super.noSuchMethod(
        Invocation.getter(#hasUseResult),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleForOverriding => (super.noSuchMethod(
        Invocation.getter(#hasVisibleForOverriding),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleForTemplate => (super.noSuchMethod(
        Invocation.getter(#hasVisibleForTemplate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleForTesting => (super.noSuchMethod(
        Invocation.getter(#hasVisibleForTesting),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleOutsideTemplate => (super.noSuchMethod(
        Invocation.getter(#hasVisibleOutsideTemplate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isPrivate => (super.noSuchMethod(
        Invocation.getter(#isPrivate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isPublic => (super.noSuchMethod(
        Invocation.getter(#isPublic),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSynthetic => (super.noSuchMethod(
        Invocation.getter(#isSynthetic),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.ElementKind get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: _FakeElementKind_1(
          this,
          Invocation.getter(#kind),
        ),
        returnValueForMissingStub: _FakeElementKind_1(
          this,
          Invocation.getter(#kind),
        ),
      ) as _i3.ElementKind);

  @override
  List<_i3.ElementAnnotation> get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: <_i3.ElementAnnotation>[],
        returnValueForMissingStub: <_i3.ElementAnnotation>[],
      ) as List<_i3.ElementAnnotation>);

  @override
  int get nameLength => (super.noSuchMethod(
        Invocation.getter(#nameLength),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get nameOffset => (super.noSuchMethod(
        Invocation.getter(#nameOffset),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i4.Element get nonSynthetic => (super.noSuchMethod(
        Invocation.getter(#nonSynthetic),
        returnValue: _FakeElement_2(
          this,
          Invocation.getter(#nonSynthetic),
        ),
        returnValueForMissingStub: _FakeElement_2(
          this,
          Invocation.getter(#nonSynthetic),
        ),
      ) as _i4.Element);

  @override
  T? accept<T>(_i4.ElementVisitor<T>? visitor) => (super.noSuchMethod(
        Invocation.method(
          #accept,
          [visitor],
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  String getDisplayString({
    bool? withNullability = true,
    bool? multiline = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDisplayString,
          [],
          {
            #withNullability: withNullability,
            #multiline: multiline,
          },
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayString,
            [],
            {
              #withNullability: withNullability,
              #multiline: multiline,
            },
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayString,
            [],
            {
              #withNullability: withNullability,
              #multiline: multiline,
            },
          ),
        ),
      ) as String);

  @override
  String getExtendedDisplayName(String? shortName) => (super.noSuchMethod(
        Invocation.method(
          #getExtendedDisplayName,
          [shortName],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getExtendedDisplayName,
            [shortName],
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getExtendedDisplayName,
            [shortName],
          ),
        ),
      ) as String);

  @override
  bool isAccessibleIn(_i4.LibraryElement? library) => (super.noSuchMethod(
        Invocation.method(
          #isAccessibleIn,
          [library],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  E? thisOrAncestorMatching<E extends _i4.Element>(
          bool Function(_i4.Element)? predicate) =>
      (super.noSuchMethod(
        Invocation.method(
          #thisOrAncestorMatching,
          [predicate],
        ),
        returnValueForMissingStub: null,
      ) as E?);

  @override
  E? thisOrAncestorMatching3<E extends _i4.Element>(
          bool Function(_i4.Element)? predicate) =>
      (super.noSuchMethod(
        Invocation.method(
          #thisOrAncestorMatching3,
          [predicate],
        ),
        returnValueForMissingStub: null,
      ) as E?);

  @override
  void visitChildren(_i4.ElementVisitor<dynamic>? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitChildren,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FileSpan].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileSpan extends _i1.Mock implements _i5.FileSpan {
  @override
  _i5.SourceFile get file => (super.noSuchMethod(
        Invocation.getter(#file),
        returnValue: _FakeSourceFile_3(
          this,
          Invocation.getter(#file),
        ),
        returnValueForMissingStub: _FakeSourceFile_3(
          this,
          Invocation.getter(#file),
        ),
      ) as _i5.SourceFile);

  @override
  _i5.FileLocation get start => (super.noSuchMethod(
        Invocation.getter(#start),
        returnValue: _FakeFileLocation_4(
          this,
          Invocation.getter(#start),
        ),
        returnValueForMissingStub: _FakeFileLocation_4(
          this,
          Invocation.getter(#start),
        ),
      ) as _i5.FileLocation);

  @override
  _i5.FileLocation get end => (super.noSuchMethod(
        Invocation.getter(#end),
        returnValue: _FakeFileLocation_4(
          this,
          Invocation.getter(#end),
        ),
        returnValueForMissingStub: _FakeFileLocation_4(
          this,
          Invocation.getter(#end),
        ),
      ) as _i5.FileLocation);

  @override
  String get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#context),
        ),
      ) as String);

  @override
  String get text => (super.noSuchMethod(
        Invocation.getter(#text),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#text),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#text),
        ),
      ) as String);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i5.FileSpan expand(_i5.FileSpan? other) => (super.noSuchMethod(
        Invocation.method(
          #expand,
          [other],
        ),
        returnValue: _FakeFileSpan_5(
          this,
          Invocation.method(
            #expand,
            [other],
          ),
        ),
        returnValueForMissingStub: _FakeFileSpan_5(
          this,
          Invocation.method(
            #expand,
            [other],
          ),
        ),
      ) as _i5.FileSpan);

  @override
  int compareTo(_i6.SourceSpan? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i6.SourceSpan union(_i6.SourceSpan? other) => (super.noSuchMethod(
        Invocation.method(
          #union,
          [other],
        ),
        returnValue: _FakeSourceSpan_6(
          this,
          Invocation.method(
            #union,
            [other],
          ),
        ),
        returnValueForMissingStub: _FakeSourceSpan_6(
          this,
          Invocation.method(
            #union,
            [other],
          ),
        ),
      ) as _i6.SourceSpan);

  @override
  String message(
    String? message, {
    Object? color,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #message,
          [message],
          {#color: color},
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #message,
            [message],
            {#color: color},
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #message,
            [message],
            {#color: color},
          ),
        ),
      ) as String);

  @override
  String highlight({Object? color}) => (super.noSuchMethod(
        Invocation.method(
          #highlight,
          [],
          {#color: color},
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #highlight,
            [],
            {#color: color},
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #highlight,
            [],
            {#color: color},
          ),
        ),
      ) as String);
}

/// A class which mocks [ParameterElement].
///
/// See the documentation for Mockito's code generation for more information.
class MockParameterElement extends _i1.Mock implements _i4.ParameterElement {
  @override
  _i4.ParameterElement get declaration => (super.noSuchMethod(
        Invocation.getter(#declaration),
        returnValue: _FakeParameterElement_7(
          this,
          Invocation.getter(#declaration),
        ),
        returnValueForMissingStub: _FakeParameterElement_7(
          this,
          Invocation.getter(#declaration),
        ),
      ) as _i4.ParameterElement);

  @override
  _i3.FormalParameterElement get element => (super.noSuchMethod(
        Invocation.getter(#element),
        returnValue: _FakeFormalParameterElement_8(
          this,
          Invocation.getter(#element),
        ),
        returnValueForMissingStub: _FakeFormalParameterElement_8(
          this,
          Invocation.getter(#element),
        ),
      ) as _i3.FormalParameterElement);

  @override
  bool get hasDefaultValue => (super.noSuchMethod(
        Invocation.getter(#hasDefaultValue),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isCovariant => (super.noSuchMethod(
        Invocation.getter(#isCovariant),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isInitializingFormal => (super.noSuchMethod(
        Invocation.getter(#isInitializingFormal),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isNamed => (super.noSuchMethod(
        Invocation.getter(#isNamed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isOptional => (super.noSuchMethod(
        Invocation.getter(#isOptional),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isOptionalNamed => (super.noSuchMethod(
        Invocation.getter(#isOptionalNamed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isOptionalPositional => (super.noSuchMethod(
        Invocation.getter(#isOptionalPositional),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isPositional => (super.noSuchMethod(
        Invocation.getter(#isPositional),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isRequired => (super.noSuchMethod(
        Invocation.getter(#isRequired),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isRequiredNamed => (super.noSuchMethod(
        Invocation.getter(#isRequiredNamed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isRequiredPositional => (super.noSuchMethod(
        Invocation.getter(#isRequiredPositional),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSuperFormal => (super.noSuchMethod(
        Invocation.getter(#isSuperFormal),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i7.ParameterKind get parameterKind => (super.noSuchMethod(
        Invocation.getter(#parameterKind),
        returnValue: _FakeParameterKind_9(
          this,
          Invocation.getter(#parameterKind),
        ),
        returnValueForMissingStub: _FakeParameterKind_9(
          this,
          Invocation.getter(#parameterKind),
        ),
      ) as _i7.ParameterKind);

  @override
  List<_i4.ParameterElement> get parameters => (super.noSuchMethod(
        Invocation.getter(#parameters),
        returnValue: <_i4.ParameterElement>[],
        returnValueForMissingStub: <_i4.ParameterElement>[],
      ) as List<_i4.ParameterElement>);

  @override
  List<_i4.TypeParameterElement> get typeParameters => (super.noSuchMethod(
        Invocation.getter(#typeParameters),
        returnValue: <_i4.TypeParameterElement>[],
        returnValueForMissingStub: <_i4.TypeParameterElement>[],
      ) as List<_i4.TypeParameterElement>);

  @override
  List<_i4.Element> get children => (super.noSuchMethod(
        Invocation.getter(#children),
        returnValue: <_i4.Element>[],
        returnValueForMissingStub: <_i4.Element>[],
      ) as List<_i4.Element>);

  @override
  _i2.AnalysisContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeAnalysisContext_0(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeAnalysisContext_0(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.AnalysisContext);

  @override
  String get displayName => (super.noSuchMethod(
        Invocation.getter(#displayName),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
      ) as String);

  @override
  bool get hasAlwaysThrows => (super.noSuchMethod(
        Invocation.getter(#hasAlwaysThrows),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDeprecated => (super.noSuchMethod(
        Invocation.getter(#hasDeprecated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDoNotStore => (super.noSuchMethod(
        Invocation.getter(#hasDoNotStore),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDoNotSubmit => (super.noSuchMethod(
        Invocation.getter(#hasDoNotSubmit),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasFactory => (super.noSuchMethod(
        Invocation.getter(#hasFactory),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasImmutable => (super.noSuchMethod(
        Invocation.getter(#hasImmutable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasInternal => (super.noSuchMethod(
        Invocation.getter(#hasInternal),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasIsTest => (super.noSuchMethod(
        Invocation.getter(#hasIsTest),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasIsTestGroup => (super.noSuchMethod(
        Invocation.getter(#hasIsTestGroup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasJS => (super.noSuchMethod(
        Invocation.getter(#hasJS),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasLiteral => (super.noSuchMethod(
        Invocation.getter(#hasLiteral),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMustBeConst => (super.noSuchMethod(
        Invocation.getter(#hasMustBeConst),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMustBeOverridden => (super.noSuchMethod(
        Invocation.getter(#hasMustBeOverridden),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMustCallSuper => (super.noSuchMethod(
        Invocation.getter(#hasMustCallSuper),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasNonVirtual => (super.noSuchMethod(
        Invocation.getter(#hasNonVirtual),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasOptionalTypeArgs => (super.noSuchMethod(
        Invocation.getter(#hasOptionalTypeArgs),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasOverride => (super.noSuchMethod(
        Invocation.getter(#hasOverride),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasProtected => (super.noSuchMethod(
        Invocation.getter(#hasProtected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasRedeclare => (super.noSuchMethod(
        Invocation.getter(#hasRedeclare),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasReopen => (super.noSuchMethod(
        Invocation.getter(#hasReopen),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasRequired => (super.noSuchMethod(
        Invocation.getter(#hasRequired),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasSealed => (super.noSuchMethod(
        Invocation.getter(#hasSealed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasUseResult => (super.noSuchMethod(
        Invocation.getter(#hasUseResult),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleForOverriding => (super.noSuchMethod(
        Invocation.getter(#hasVisibleForOverriding),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleForTemplate => (super.noSuchMethod(
        Invocation.getter(#hasVisibleForTemplate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleForTesting => (super.noSuchMethod(
        Invocation.getter(#hasVisibleForTesting),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleOutsideTemplate => (super.noSuchMethod(
        Invocation.getter(#hasVisibleOutsideTemplate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isPrivate => (super.noSuchMethod(
        Invocation.getter(#isPrivate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isPublic => (super.noSuchMethod(
        Invocation.getter(#isPublic),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSynthetic => (super.noSuchMethod(
        Invocation.getter(#isSynthetic),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.ElementKind get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: _FakeElementKind_1(
          this,
          Invocation.getter(#kind),
        ),
        returnValueForMissingStub: _FakeElementKind_1(
          this,
          Invocation.getter(#kind),
        ),
      ) as _i3.ElementKind);

  @override
  List<_i3.ElementAnnotation> get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: <_i3.ElementAnnotation>[],
        returnValueForMissingStub: <_i3.ElementAnnotation>[],
      ) as List<_i3.ElementAnnotation>);

  @override
  int get nameLength => (super.noSuchMethod(
        Invocation.getter(#nameLength),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get nameOffset => (super.noSuchMethod(
        Invocation.getter(#nameOffset),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i4.Element get nonSynthetic => (super.noSuchMethod(
        Invocation.getter(#nonSynthetic),
        returnValue: _FakeElement_2(
          this,
          Invocation.getter(#nonSynthetic),
        ),
        returnValueForMissingStub: _FakeElement_2(
          this,
          Invocation.getter(#nonSynthetic),
        ),
      ) as _i4.Element);

  @override
  bool get hasImplicitType => (super.noSuchMethod(
        Invocation.getter(#hasImplicitType),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isConst => (super.noSuchMethod(
        Invocation.getter(#isConst),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isFinal => (super.noSuchMethod(
        Invocation.getter(#isFinal),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isLate => (super.noSuchMethod(
        Invocation.getter(#isLate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isStatic => (super.noSuchMethod(
        Invocation.getter(#isStatic),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i8.DartType get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _FakeDartType_10(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _FakeDartType_10(
          this,
          Invocation.getter(#type),
        ),
      ) as _i8.DartType);

  @override
  bool get isConstantEvaluated => (super.noSuchMethod(
        Invocation.getter(#isConstantEvaluated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void appendToWithoutDelimiters(
    StringBuffer? buffer, {
    bool? withNullability = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #appendToWithoutDelimiters,
          [buffer],
          {#withNullability: withNullability},
        ),
        returnValueForMissingStub: null,
      );

  @override
  T? accept<T>(_i4.ElementVisitor<T>? visitor) => (super.noSuchMethod(
        Invocation.method(
          #accept,
          [visitor],
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  String getDisplayString({
    bool? withNullability = true,
    bool? multiline = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDisplayString,
          [],
          {
            #withNullability: withNullability,
            #multiline: multiline,
          },
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayString,
            [],
            {
              #withNullability: withNullability,
              #multiline: multiline,
            },
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayString,
            [],
            {
              #withNullability: withNullability,
              #multiline: multiline,
            },
          ),
        ),
      ) as String);

  @override
  String getExtendedDisplayName(String? shortName) => (super.noSuchMethod(
        Invocation.method(
          #getExtendedDisplayName,
          [shortName],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getExtendedDisplayName,
            [shortName],
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getExtendedDisplayName,
            [shortName],
          ),
        ),
      ) as String);

  @override
  bool isAccessibleIn(_i4.LibraryElement? library) => (super.noSuchMethod(
        Invocation.method(
          #isAccessibleIn,
          [library],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  E? thisOrAncestorMatching<E extends _i4.Element>(
          bool Function(_i4.Element)? predicate) =>
      (super.noSuchMethod(
        Invocation.method(
          #thisOrAncestorMatching,
          [predicate],
        ),
        returnValueForMissingStub: null,
      ) as E?);

  @override
  E? thisOrAncestorMatching3<E extends _i4.Element>(
          bool Function(_i4.Element)? predicate) =>
      (super.noSuchMethod(
        Invocation.method(
          #thisOrAncestorMatching3,
          [predicate],
        ),
        returnValueForMissingStub: null,
      ) as E?);

  @override
  void visitChildren(_i4.ElementVisitor<dynamic>? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitChildren,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EnumElement].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnumElement extends _i1.Mock implements _i4.EnumElement {
  @override
  _i4.AugmentedEnumElement get augmented => (super.noSuchMethod(
        Invocation.getter(#augmented),
        returnValue: _FakeAugmentedEnumElement_11(
          this,
          Invocation.getter(#augmented),
        ),
        returnValueForMissingStub: _FakeAugmentedEnumElement_11(
          this,
          Invocation.getter(#augmented),
        ),
      ) as _i4.AugmentedEnumElement);

  @override
  List<_i8.InterfaceType> get allSupertypes => (super.noSuchMethod(
        Invocation.getter(#allSupertypes),
        returnValue: <_i8.InterfaceType>[],
        returnValueForMissingStub: <_i8.InterfaceType>[],
      ) as List<_i8.InterfaceType>);

  @override
  List<_i4.ConstructorElement> get constructors => (super.noSuchMethod(
        Invocation.getter(#constructors),
        returnValue: <_i4.ConstructorElement>[],
        returnValueForMissingStub: <_i4.ConstructorElement>[],
      ) as List<_i4.ConstructorElement>);

  @override
  List<_i8.InterfaceType> get interfaces => (super.noSuchMethod(
        Invocation.getter(#interfaces),
        returnValue: <_i8.InterfaceType>[],
        returnValueForMissingStub: <_i8.InterfaceType>[],
      ) as List<_i8.InterfaceType>);

  @override
  List<_i8.InterfaceType> get mixins => (super.noSuchMethod(
        Invocation.getter(#mixins),
        returnValue: <_i8.InterfaceType>[],
        returnValueForMissingStub: <_i8.InterfaceType>[],
      ) as List<_i8.InterfaceType>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i8.InterfaceType get thisType => (super.noSuchMethod(
        Invocation.getter(#thisType),
        returnValue: _FakeInterfaceType_12(
          this,
          Invocation.getter(#thisType),
        ),
        returnValueForMissingStub: _FakeInterfaceType_12(
          this,
          Invocation.getter(#thisType),
        ),
      ) as _i8.InterfaceType);

  @override
  List<_i4.PropertyAccessorElement> get accessors => (super.noSuchMethod(
        Invocation.getter(#accessors),
        returnValue: <_i4.PropertyAccessorElement>[],
        returnValueForMissingStub: <_i4.PropertyAccessorElement>[],
      ) as List<_i4.PropertyAccessorElement>);

  @override
  _i4.CompilationUnitElement get enclosingElement => (super.noSuchMethod(
        Invocation.getter(#enclosingElement),
        returnValue: _FakeCompilationUnitElement_13(
          this,
          Invocation.getter(#enclosingElement),
        ),
        returnValueForMissingStub: _FakeCompilationUnitElement_13(
          this,
          Invocation.getter(#enclosingElement),
        ),
      ) as _i4.CompilationUnitElement);

  @override
  _i4.CompilationUnitElement get enclosingElement3 => (super.noSuchMethod(
        Invocation.getter(#enclosingElement3),
        returnValue: _FakeCompilationUnitElement_13(
          this,
          Invocation.getter(#enclosingElement3),
        ),
        returnValueForMissingStub: _FakeCompilationUnitElement_13(
          this,
          Invocation.getter(#enclosingElement3),
        ),
      ) as _i4.CompilationUnitElement);

  @override
  List<_i4.FieldElement> get fields => (super.noSuchMethod(
        Invocation.getter(#fields),
        returnValue: <_i4.FieldElement>[],
        returnValueForMissingStub: <_i4.FieldElement>[],
      ) as List<_i4.FieldElement>);

  @override
  bool get isAugmentation => (super.noSuchMethod(
        Invocation.getter(#isAugmentation),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i4.MethodElement> get methods => (super.noSuchMethod(
        Invocation.getter(#methods),
        returnValue: <_i4.MethodElement>[],
        returnValueForMissingStub: <_i4.MethodElement>[],
      ) as List<_i4.MethodElement>);

  @override
  List<_i4.Element> get children => (super.noSuchMethod(
        Invocation.getter(#children),
        returnValue: <_i4.Element>[],
        returnValueForMissingStub: <_i4.Element>[],
      ) as List<_i4.Element>);

  @override
  _i2.AnalysisContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeAnalysisContext_0(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeAnalysisContext_0(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.AnalysisContext);

  @override
  _i4.Element get declaration => (super.noSuchMethod(
        Invocation.getter(#declaration),
        returnValue: _FakeElement_2(
          this,
          Invocation.getter(#declaration),
        ),
        returnValueForMissingStub: _FakeElement_2(
          this,
          Invocation.getter(#declaration),
        ),
      ) as _i4.Element);

  @override
  String get displayName => (super.noSuchMethod(
        Invocation.getter(#displayName),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
      ) as String);

  @override
  bool get hasAlwaysThrows => (super.noSuchMethod(
        Invocation.getter(#hasAlwaysThrows),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDeprecated => (super.noSuchMethod(
        Invocation.getter(#hasDeprecated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDoNotStore => (super.noSuchMethod(
        Invocation.getter(#hasDoNotStore),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDoNotSubmit => (super.noSuchMethod(
        Invocation.getter(#hasDoNotSubmit),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasFactory => (super.noSuchMethod(
        Invocation.getter(#hasFactory),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasImmutable => (super.noSuchMethod(
        Invocation.getter(#hasImmutable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasInternal => (super.noSuchMethod(
        Invocation.getter(#hasInternal),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasIsTest => (super.noSuchMethod(
        Invocation.getter(#hasIsTest),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasIsTestGroup => (super.noSuchMethod(
        Invocation.getter(#hasIsTestGroup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasJS => (super.noSuchMethod(
        Invocation.getter(#hasJS),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasLiteral => (super.noSuchMethod(
        Invocation.getter(#hasLiteral),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMustBeConst => (super.noSuchMethod(
        Invocation.getter(#hasMustBeConst),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMustBeOverridden => (super.noSuchMethod(
        Invocation.getter(#hasMustBeOverridden),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMustCallSuper => (super.noSuchMethod(
        Invocation.getter(#hasMustCallSuper),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasNonVirtual => (super.noSuchMethod(
        Invocation.getter(#hasNonVirtual),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasOptionalTypeArgs => (super.noSuchMethod(
        Invocation.getter(#hasOptionalTypeArgs),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasOverride => (super.noSuchMethod(
        Invocation.getter(#hasOverride),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasProtected => (super.noSuchMethod(
        Invocation.getter(#hasProtected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasRedeclare => (super.noSuchMethod(
        Invocation.getter(#hasRedeclare),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasReopen => (super.noSuchMethod(
        Invocation.getter(#hasReopen),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasRequired => (super.noSuchMethod(
        Invocation.getter(#hasRequired),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasSealed => (super.noSuchMethod(
        Invocation.getter(#hasSealed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasUseResult => (super.noSuchMethod(
        Invocation.getter(#hasUseResult),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleForOverriding => (super.noSuchMethod(
        Invocation.getter(#hasVisibleForOverriding),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleForTemplate => (super.noSuchMethod(
        Invocation.getter(#hasVisibleForTemplate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleForTesting => (super.noSuchMethod(
        Invocation.getter(#hasVisibleForTesting),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasVisibleOutsideTemplate => (super.noSuchMethod(
        Invocation.getter(#hasVisibleOutsideTemplate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isPrivate => (super.noSuchMethod(
        Invocation.getter(#isPrivate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isPublic => (super.noSuchMethod(
        Invocation.getter(#isPublic),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSynthetic => (super.noSuchMethod(
        Invocation.getter(#isSynthetic),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.ElementKind get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: _FakeElementKind_1(
          this,
          Invocation.getter(#kind),
        ),
        returnValueForMissingStub: _FakeElementKind_1(
          this,
          Invocation.getter(#kind),
        ),
      ) as _i3.ElementKind);

  @override
  _i4.LibraryElement get library => (super.noSuchMethod(
        Invocation.getter(#library),
        returnValue: _FakeLibraryElement_14(
          this,
          Invocation.getter(#library),
        ),
        returnValueForMissingStub: _FakeLibraryElement_14(
          this,
          Invocation.getter(#library),
        ),
      ) as _i4.LibraryElement);

  @override
  List<_i3.ElementAnnotation> get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: <_i3.ElementAnnotation>[],
        returnValueForMissingStub: <_i3.ElementAnnotation>[],
      ) as List<_i3.ElementAnnotation>);

  @override
  int get nameLength => (super.noSuchMethod(
        Invocation.getter(#nameLength),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get nameOffset => (super.noSuchMethod(
        Invocation.getter(#nameOffset),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i4.Element get nonSynthetic => (super.noSuchMethod(
        Invocation.getter(#nonSynthetic),
        returnValue: _FakeElement_2(
          this,
          Invocation.getter(#nonSynthetic),
        ),
        returnValueForMissingStub: _FakeElement_2(
          this,
          Invocation.getter(#nonSynthetic),
        ),
      ) as _i4.Element);

  @override
  _i9.Source get source => (super.noSuchMethod(
        Invocation.getter(#source),
        returnValue: _FakeSource_15(
          this,
          Invocation.getter(#source),
        ),
        returnValueForMissingStub: _FakeSource_15(
          this,
          Invocation.getter(#source),
        ),
      ) as _i9.Source);

  @override
  _i9.Source get librarySource => (super.noSuchMethod(
        Invocation.getter(#librarySource),
        returnValue: _FakeSource_15(
          this,
          Invocation.getter(#librarySource),
        ),
        returnValueForMissingStub: _FakeSource_15(
          this,
          Invocation.getter(#librarySource),
        ),
      ) as _i9.Source);

  @override
  bool get isSimplyBounded => (super.noSuchMethod(
        Invocation.getter(#isSimplyBounded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i4.TypeParameterElement> get typeParameters => (super.noSuchMethod(
        Invocation.getter(#typeParameters),
        returnValue: <_i4.TypeParameterElement>[],
        returnValueForMissingStub: <_i4.TypeParameterElement>[],
      ) as List<_i4.TypeParameterElement>);

  @override
  _i4.FieldElement? getField(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getField,
          [name],
        ),
        returnValueForMissingStub: null,
      ) as _i4.FieldElement?);

  @override
  _i4.PropertyAccessorElement? getGetter(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getGetter,
          [name],
        ),
        returnValueForMissingStub: null,
      ) as _i4.PropertyAccessorElement?);

  @override
  _i4.MethodElement? getMethod(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getMethod,
          [name],
        ),
        returnValueForMissingStub: null,
      ) as _i4.MethodElement?);

  @override
  _i4.ConstructorElement? getNamedConstructor(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNamedConstructor,
          [name],
        ),
        returnValueForMissingStub: null,
      ) as _i4.ConstructorElement?);

  @override
  _i4.PropertyAccessorElement? getSetter(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getSetter,
          [name],
        ),
        returnValueForMissingStub: null,
      ) as _i4.PropertyAccessorElement?);

  @override
  _i8.InterfaceType instantiate({
    required List<_i8.DartType>? typeArguments,
    required _i13.NullabilitySuffix? nullabilitySuffix,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #instantiate,
          [],
          {
            #typeArguments: typeArguments,
            #nullabilitySuffix: nullabilitySuffix,
          },
        ),
        returnValue: _FakeInterfaceType_12(
          this,
          Invocation.method(
            #instantiate,
            [],
            {
              #typeArguments: typeArguments,
              #nullabilitySuffix: nullabilitySuffix,
            },
          ),
        ),
        returnValueForMissingStub: _FakeInterfaceType_12(
          this,
          Invocation.method(
            #instantiate,
            [],
            {
              #typeArguments: typeArguments,
              #nullabilitySuffix: nullabilitySuffix,
            },
          ),
        ),
      ) as _i8.InterfaceType);

  @override
  _i4.MethodElement? lookUpConcreteMethod(
    String? methodName,
    _i4.LibraryElement? library,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookUpConcreteMethod,
          [
            methodName,
            library,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i4.MethodElement?);

  @override
  _i4.PropertyAccessorElement? lookUpGetter(
    String? getterName,
    _i4.LibraryElement? library,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookUpGetter,
          [
            getterName,
            library,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i4.PropertyAccessorElement?);

  @override
  _i4.PropertyAccessorElement? lookUpInheritedConcreteGetter(
    String? getterName,
    _i4.LibraryElement? library,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookUpInheritedConcreteGetter,
          [
            getterName,
            library,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i4.PropertyAccessorElement?);

  @override
  _i4.MethodElement? lookUpInheritedConcreteMethod(
    String? methodName,
    _i4.LibraryElement? library,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookUpInheritedConcreteMethod,
          [
            methodName,
            library,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i4.MethodElement?);

  @override
  _i4.PropertyAccessorElement? lookUpInheritedConcreteSetter(
    String? setterName,
    _i4.LibraryElement? library,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookUpInheritedConcreteSetter,
          [
            setterName,
            library,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i4.PropertyAccessorElement?);

  @override
  _i4.MethodElement? lookUpInheritedMethod(
    String? methodName,
    _i4.LibraryElement? library,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookUpInheritedMethod,
          [
            methodName,
            library,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i4.MethodElement?);

  @override
  _i4.MethodElement? lookUpMethod(
    String? methodName,
    _i4.LibraryElement? library,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookUpMethod,
          [
            methodName,
            library,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i4.MethodElement?);

  @override
  _i4.PropertyAccessorElement? lookUpSetter(
    String? setterName,
    _i4.LibraryElement? library,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookUpSetter,
          [
            setterName,
            library,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i4.PropertyAccessorElement?);

  @override
  T? accept<T>(_i4.ElementVisitor<T>? visitor) => (super.noSuchMethod(
        Invocation.method(
          #accept,
          [visitor],
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  String getDisplayString({
    bool? withNullability = true,
    bool? multiline = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDisplayString,
          [],
          {
            #withNullability: withNullability,
            #multiline: multiline,
          },
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayString,
            [],
            {
              #withNullability: withNullability,
              #multiline: multiline,
            },
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayString,
            [],
            {
              #withNullability: withNullability,
              #multiline: multiline,
            },
          ),
        ),
      ) as String);

  @override
  String getExtendedDisplayName(String? shortName) => (super.noSuchMethod(
        Invocation.method(
          #getExtendedDisplayName,
          [shortName],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getExtendedDisplayName,
            [shortName],
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getExtendedDisplayName,
            [shortName],
          ),
        ),
      ) as String);

  @override
  bool isAccessibleIn(_i4.LibraryElement? library) => (super.noSuchMethod(
        Invocation.method(
          #isAccessibleIn,
          [library],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  E? thisOrAncestorMatching<E extends _i4.Element>(
          bool Function(_i4.Element)? predicate) =>
      (super.noSuchMethod(
        Invocation.method(
          #thisOrAncestorMatching,
          [predicate],
        ),
        returnValueForMissingStub: null,
      ) as E?);

  @override
  E? thisOrAncestorMatching3<E extends _i4.Element>(
          bool Function(_i4.Element)? predicate) =>
      (super.noSuchMethod(
        Invocation.method(
          #thisOrAncestorMatching3,
          [predicate],
        ),
        returnValueForMissingStub: null,
      ) as E?);

  @override
  void visitChildren(_i4.ElementVisitor<dynamic>? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitChildren,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DartType].
///
/// See the documentation for Mockito's code generation for more information.
class MockDartType extends _i1.Mock implements _i8.DartType {
  @override
  _i8.DartType get extensionTypeErasure => (super.noSuchMethod(
        Invocation.getter(#extensionTypeErasure),
        returnValue: _FakeDartType_10(
          this,
          Invocation.getter(#extensionTypeErasure),
        ),
        returnValueForMissingStub: _FakeDartType_10(
          this,
          Invocation.getter(#extensionTypeErasure),
        ),
      ) as _i8.DartType);

  @override
  bool get isBottom => (super.noSuchMethod(
        Invocation.getter(#isBottom),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartAsyncFuture => (super.noSuchMethod(
        Invocation.getter(#isDartAsyncFuture),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartAsyncFutureOr => (super.noSuchMethod(
        Invocation.getter(#isDartAsyncFutureOr),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartAsyncStream => (super.noSuchMethod(
        Invocation.getter(#isDartAsyncStream),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreBool => (super.noSuchMethod(
        Invocation.getter(#isDartCoreBool),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreDouble => (super.noSuchMethod(
        Invocation.getter(#isDartCoreDouble),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreEnum => (super.noSuchMethod(
        Invocation.getter(#isDartCoreEnum),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreFunction => (super.noSuchMethod(
        Invocation.getter(#isDartCoreFunction),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreInt => (super.noSuchMethod(
        Invocation.getter(#isDartCoreInt),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreIterable => (super.noSuchMethod(
        Invocation.getter(#isDartCoreIterable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreList => (super.noSuchMethod(
        Invocation.getter(#isDartCoreList),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreMap => (super.noSuchMethod(
        Invocation.getter(#isDartCoreMap),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreNull => (super.noSuchMethod(
        Invocation.getter(#isDartCoreNull),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreNum => (super.noSuchMethod(
        Invocation.getter(#isDartCoreNum),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreObject => (super.noSuchMethod(
        Invocation.getter(#isDartCoreObject),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreRecord => (super.noSuchMethod(
        Invocation.getter(#isDartCoreRecord),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreSet => (super.noSuchMethod(
        Invocation.getter(#isDartCoreSet),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreString => (super.noSuchMethod(
        Invocation.getter(#isDartCoreString),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreSymbol => (super.noSuchMethod(
        Invocation.getter(#isDartCoreSymbol),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDartCoreType => (super.noSuchMethod(
        Invocation.getter(#isDartCoreType),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDynamic => (super.noSuchMethod(
        Invocation.getter(#isDynamic),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isVoid => (super.noSuchMethod(
        Invocation.getter(#isVoid),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i13.NullabilitySuffix get nullabilitySuffix => (super.noSuchMethod(
        Invocation.getter(#nullabilitySuffix),
        returnValue: _i13.NullabilitySuffix.question,
        returnValueForMissingStub: _i13.NullabilitySuffix.question,
      ) as _i13.NullabilitySuffix);

  @override
  R accept<R>(_i14.TypeVisitor<R>? visitor) => (super.noSuchMethod(
        Invocation.method(
          #accept,
          [visitor],
        ),
        returnValue: _i12.dummyValue<R>(
          this,
          Invocation.method(
            #accept,
            [visitor],
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<R>(
          this,
          Invocation.method(
            #accept,
            [visitor],
          ),
        ),
      ) as R);

  @override
  R acceptWithArgument<R, A>(
    _i14.TypeVisitorWithArgument<R, A>? visitor,
    A? argument,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptWithArgument,
          [
            visitor,
            argument,
          ],
        ),
        returnValue: _i12.dummyValue<R>(
          this,
          Invocation.method(
            #acceptWithArgument,
            [
              visitor,
              argument,
            ],
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<R>(
          this,
          Invocation.method(
            #acceptWithArgument,
            [
              visitor,
              argument,
            ],
          ),
        ),
      ) as R);

  @override
  _i8.InterfaceType? asInstanceOf(_i4.InterfaceElement? element) =>
      (super.noSuchMethod(
        Invocation.method(
          #asInstanceOf,
          [element],
        ),
        returnValueForMissingStub: null,
      ) as _i8.InterfaceType?);

  @override
  _i8.InterfaceType? asInstanceOf2(_i3.InterfaceElement2? element) =>
      (super.noSuchMethod(
        Invocation.method(
          #asInstanceOf2,
          [element],
        ),
        returnValueForMissingStub: null,
      ) as _i8.InterfaceType?);

  @override
  String getDisplayString({bool? withNullability = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDisplayString,
          [],
          {#withNullability: withNullability},
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayString,
            [],
            {#withNullability: withNullability},
          ),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayString,
            [],
            {#withNullability: withNullability},
          ),
        ),
      ) as String);

  @override
  _i8.DartType resolveToBound(_i8.DartType? objectType) => (super.noSuchMethod(
        Invocation.method(
          #resolveToBound,
          [objectType],
        ),
        returnValue: _FakeDartType_10(
          this,
          Invocation.method(
            #resolveToBound,
            [objectType],
          ),
        ),
        returnValueForMissingStub: _FakeDartType_10(
          this,
          Invocation.method(
            #resolveToBound,
            [objectType],
          ),
        ),
      ) as _i8.DartType);

  @override
  bool isStructurallyEqualTo(_i15.SharedTypeStructure<_i8.DartType>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #isStructurallyEqualTo,
          [other],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [ExpressionConverterUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpressionConverterUtil extends _i1.Mock
    implements _i16.ExpressionConverterUtil {
  @override
  _i17.ValueResponse<(String, _i18.EExpressionType)> parseExpression(
    _i19.Expression? expression,
    _i4.Element? element, {
    bool? asExpression = true,
    required List<_i4.ParameterElement>? parameters,
    required _i18.TableSelector? selector,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseExpression,
          [
            expression,
            element,
          ],
          {
            #asExpression: asExpression,
            #parameters: parameters,
            #selector: selector,
          },
        ),
        returnValue:
            _i12.dummyValue<_i17.ValueResponse<(String, _i18.EExpressionType)>>(
          this,
          Invocation.method(
            #parseExpression,
            [
              expression,
              element,
            ],
            {
              #asExpression: asExpression,
              #parameters: parameters,
              #selector: selector,
            },
          ),
        ),
        returnValueForMissingStub:
            _i12.dummyValue<_i17.ValueResponse<(String, _i18.EExpressionType)>>(
          this,
          Invocation.method(
            #parseExpression,
            [
              expression,
              element,
            ],
            {
              #asExpression: asExpression,
              #parameters: parameters,
              #selector: selector,
            },
          ),
        ),
      ) as _i17.ValueResponse<(String, _i18.EExpressionType)>);
}

/// A class which mocks [ClassState].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassState extends _i1.Mock implements _i10.ClassState {
  @override
  String get className => (super.noSuchMethod(
        Invocation.getter(#className),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#className),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#className),
        ),
      ) as String);

  @override
  _i8.DartType get classType => (super.noSuchMethod(
        Invocation.getter(#classType),
        returnValue: _FakeDartType_10(
          this,
          Invocation.getter(#classType),
        ),
        returnValueForMissingStub: _FakeDartType_10(
          this,
          Invocation.getter(#classType),
        ),
      ) as _i8.DartType);

  @override
  Set<_i4.ClassElement> get superClasses => (super.noSuchMethod(
        Invocation.getter(#superClasses),
        returnValue: <_i4.ClassElement>{},
        returnValueForMissingStub: <_i4.ClassElement>{},
      ) as Set<_i4.ClassElement>);

  @override
  Set<_i10.TypeConverterState> get usedTypeConverters => (super.noSuchMethod(
        Invocation.getter(#usedTypeConverters),
        returnValue: <_i10.TypeConverterState>{},
        returnValueForMissingStub: <_i10.TypeConverterState>{},
      ) as Set<_i10.TypeConverterState>);

  @override
  Set<_i10.FieldState> get allFieldStates => (super.noSuchMethod(
        Invocation.getter(#allFieldStates),
        returnValue: <_i10.FieldState>{},
        returnValueForMissingStub: <_i10.FieldState>{},
      ) as Set<_i10.FieldState>);

  @override
  String get sqlTablename => (super.noSuchMethod(
        Invocation.getter(#sqlTablename),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#sqlTablename),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#sqlTablename),
        ),
      ) as String);

  @override
  _i10.ClassState copyWith({
    String? className,
    _i8.DartType? classType,
    Set<_i10.FieldState>? fieldStates,
    String? renamed,
    Set<_i4.ClassElement>? superClasses,
    Set<_i10.ClassState>? superStates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #className: className,
            #classType: classType,
            #fieldStates: fieldStates,
            #renamed: renamed,
            #superClasses: superClasses,
            #superStates: superStates,
          },
        ),
        returnValue: _FakeClassState_16(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #className: className,
              #classType: classType,
              #fieldStates: fieldStates,
              #renamed: renamed,
              #superClasses: superClasses,
              #superStates: superStates,
            },
          ),
        ),
        returnValueForMissingStub: _FakeClassState_16(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #className: className,
              #classType: classType,
              #fieldStates: fieldStates,
              #renamed: renamed,
              #superClasses: superClasses,
              #superStates: superStates,
            },
          ),
        ),
      ) as _i10.ClassState);
}

/// A class which mocks [FieldState].
///
/// See the documentation for Mockito's code generation for more information.
class MockFieldState extends _i1.Mock implements _i10.FieldState {
  @override
  String get fieldName => (super.noSuchMethod(
        Invocation.getter(#fieldName),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#fieldName),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#fieldName),
        ),
      ) as String);

  @override
  _i4.FieldElement get fieldElement => (super.noSuchMethod(
        Invocation.getter(#fieldElement),
        returnValue: _FakeFieldElement_17(
          this,
          Invocation.getter(#fieldElement),
        ),
        returnValueForMissingStub: _FakeFieldElement_17(
          this,
          Invocation.getter(#fieldElement),
        ),
      ) as _i4.FieldElement);

  @override
  bool get isConverted => (super.noSuchMethod(
        Invocation.getter(#isConverted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get sqlColumnName => (super.noSuchMethod(
        Invocation.getter(#sqlColumnName),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#sqlColumnName),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#sqlColumnName),
        ),
      ) as String);
}

/// A class which mocks [FileSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileSource extends _i1.Mock implements _i20.FileSource {
  @override
  Uri get uri => (super.noSuchMethod(
        Invocation.getter(#uri),
        returnValue: _FakeUri_18(
          this,
          Invocation.getter(#uri),
        ),
        returnValueForMissingStub: _FakeUri_18(
          this,
          Invocation.getter(#uri),
        ),
      ) as Uri);

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i11.File get file => (super.noSuchMethod(
        Invocation.getter(#file),
        returnValue: _FakeFile_19(
          this,
          Invocation.getter(#file),
        ),
        returnValueForMissingStub: _FakeFile_19(
          this,
          Invocation.getter(#file),
        ),
      ) as _i11.File);

  @override
  _i2.TimestampedData<String> get contents => (super.noSuchMethod(
        Invocation.getter(#contents),
        returnValue: _FakeTimestampedData_20<String>(
          this,
          Invocation.getter(#contents),
        ),
        returnValueForMissingStub: _FakeTimestampedData_20<String>(
          this,
          Invocation.getter(#contents),
        ),
      ) as _i2.TimestampedData<String>);

  @override
  _i2.TimestampedData<String> get contentsFromFile => (super.noSuchMethod(
        Invocation.getter(#contentsFromFile),
        returnValue: _FakeTimestampedData_20<String>(
          this,
          Invocation.getter(#contentsFromFile),
        ),
        returnValueForMissingStub: _FakeTimestampedData_20<String>(
          this,
          Invocation.getter(#contentsFromFile),
        ),
      ) as _i2.TimestampedData<String>);

  @override
  String get fullName => (super.noSuchMethod(
        Invocation.getter(#fullName),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#fullName),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#fullName),
        ),
      ) as String);

  @override
  String get shortName => (super.noSuchMethod(
        Invocation.getter(#shortName),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#shortName),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#shortName),
        ),
      ) as String);

  @override
  bool exists() => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
